### PR TITLE
Close Darwinia <> Parallel

### PR DESCRIPTION
**Pull request by jiguantong**
- [x] sovereign account 13YMK2ei1mSnnHfZRqweboFRPTzvQEo6xdjhdycF496KBnPg Transferable: 75DOT > 2DOT

### close call data
```
0x1a0008210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01283c02dc070000fe070000140d010004000100f91f210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01283c02fe070000dc070000140d010004000100f91f
```

### CODE REVIEW

**Comment by jiguantong** [comment]
image
image

**Comment by acgxv** [comment]
I think we can delete that record directly.

**Comment by acgxv** [comment]
And I think the batch call will encounter an error at https://github.com/paritytech/polkadot-sdk/blob/13a7ae77397d99b09f7b4ee99af212a3e09eb8f3/polkadot/runtime/parachains/src/hrmp.rs#L1617-L1621.

I think it's sufficient to close the Parallel > Darwinia first.

**Comment by jiguantong** [comment]
> And I think the batch call will encounter an error at https://github.com/paritytech/polkadot-sdk/blob/13a7ae77397d99b09f7b4ee99af212a3e09eb8f3/polkadot/runtime/parachains/src/hrmp.rs#L1617-L1621.
> 
> I think it's sufficient to close the Parallel > Darwinia first.

2012>2046 and 2046 > 2012 are two channels, why does it fail here?

**Pull request merged**
