### PR TITLE
Darwinia > Astar

### PR DESCRIPTION
**Pull request by jiguantong**
- [x] sovereign account `13YMK2ei1mSnnHfZRqweboFRPTzvQEo6xdjhdycF496KBnPg` Transferable DOT (currently 110.06) > 11 DOT

### CODE REVIEW

**Comment by acgxv** [comment]
> 10.06DOT > 11 DOT

Mistake?

**Comment by jiguantong** [comment]
> > 10.06DOT > 11 DOT
> 
> Mistake?

No, this is a requirement, check the box if this requirement is met, and than we can continue.

**Comment by acgxv** [comment]
Please check again.

**Comment by jiguantong** [comment]
> Please check again.

It's ok

**Pull request merged**
